name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Extract version from csproj
      id: get_version
      run: |
        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" Beblia.Sharp/Beblia.Sharp.csproj)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Pack NuGet package
      run: dotnet pack Beblia.Sharp/Beblia.Sharp.csproj --configuration Release --no-build --output ./artifacts
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Release version ${{ steps.get_version.outputs.version }}
          
          ## NuGet Package
          - Beblia.Sharp.${{ steps.get_version.outputs.version }}.nupkg
          
          ## DLL
          - Beblia.Sharp.dll (netstandard2.1)
        draft: false
        prerelease: false
        
    - name: Upload NuGet Package to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/Beblia.Sharp.${{ steps.get_version.outputs.version }}.nupkg
        asset_name: Beblia.Sharp.${{ steps.get_version.outputs.version }}.nupkg
        asset_content_type: application/zip
        
    - name: Upload DLL to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Beblia.Sharp/bin/Release/netstandard2.1/Beblia.Sharp.dll
        asset_name: Beblia.Sharp.dll
        asset_content_type: application/octet-stream
